### ISSUE TITLE
Sample using Search

### ISSUE THREAD

**Issue by jpalo** [gunjandatta/sprest#54]
Hi,
Any sample how to use Search would be appreciated. It isn't quite obvious how to make a simple search query.

Thank you!

**Comment by ndelacour** [comment]
Hi,
I think this is due to a bug. I tried the following statements:
`var mysearch = (new $REST.Search());
mysearch.searchquery({querytext:'test'}).execute();`
This executes the search but does not take into account the querytext parameter.

If I try the following:
`var mysearch = (new $REST.Search());
mysearch.searchquery("querytext=test"}).execute();`
it adds a query parameter for each letter : 
`query(0='q',%201='u',%202='e',%203='r',%204='y',%205='t',%206='e',%207='x',%208='t',%209='=',%2010='t',%2011='e',%2012='s',%2013='t')`

I think that the first methode should be the right way to call the function.

I have the feeling that line 88 of the file methodInfo.ts is causing the issue:
`for (var i = 0; i < this.methodInfo.argNames.length && i < this.methodInfo.argValues.length; i++) {`
The `this.methodInfo.argValues.length` returns an **undefined**.

You could try to replace it with the following `Object.keys(this.methodInfo.argValues).length`.  Note : I did **not** test this (yet), nor do I know what effect this will have on other calls.

**Comment by gunjandatta** [comment]
@ndelacour refer to the release notes for [v1.9.6](https://github.com/gunjandatta/sprest/releases/tag/1.9.6), it gives an update for the $REST object. Many developers requested to remove the need of creating a new object. Refer to the examples below. Sorry for any confusion on this, I think all documentation has been updated to reflect this. Thank you for posting the code example, it was a correct example for the earlier versions of the library. 👍 

@jpalo Below are code examples of executing a search request. I have a little info on this in the wiki, so you can refer to the info [here](https://github.com/gunjandatta/sprest/wiki/Search). The settings property which is passed into the query, postquery and suggest methods are available [here](https://github.com/gunjandatta/sprest/wiki/Search-Query). [MS search api documentation](https://docs.microsoft.com/en-us/sharepoint/dev/general-development/sharepoint-search-rest-api-overview) for additional information of the available methods, properties and examples.

@jpalo I generally execute requests in the browser window to test queries. This helps me during development, since I can ensure the request works prior to deploying the solution/app/add-in. I'm not sure if you are interested in a people picker search as well, but thought it's worth mentioning. Refer to this [blog post](http://dattabase.com/sharepoint-people-picker-rest-api/) for details on the people picker rest api.

### JavaScript
```
var $REST = require("gd-sprest");

// Asynchronous Request
$REST.Search().query({ Querytext: "test" }).execute(function (results) {
   // Code goes here
});
```

### Browser Console Window
```
// Synchronous Request
var results = $REST.query({ Querytext: "test" }).executeAndWait()
```

### Typescript
```
import { Search } from "gd-sprest";

(new Search()).query({ Querytext: "test" }).execute(results => {
  // Code goes here
});
```

I hope this helps give an explanation of how to use the library. If you have any problems or issues, please let me know and I'll take a look at it asap. If this solves the issue, please feel free to close it.

**Comment by ndelacour** [comment]
I did some additional testing/debugging today, using the browser window. The problem with the searchquery methode commes from the way the executeMethod is called for the search:
'    /** The search query method */
    searchquery(settings) {
        // Execute the request
        return this.executeMethod("query", {
            argNames: this.getArgNames(settings),
            name: "query",
            requestType: RequestType.GetWithArgs
        }, settings);
    }
'
The settings is an object with the keys and values. In the executeMethode an array with values only is expected and used as the arguments.

Compared with my prior response, I changed just this call to fix the url for the search, supplying only an array with values instead:
', Object.values(settings));'

**Comment by gunjandatta** [comment]
@ndelacour You're right. The search class has 2 methods outside of the mapper (searchquery and suggest). I generally do a postquery, since the settings are passed in the body of the request instead of the url as a querystring. I believe I had an error w/ GET requests (searchquery) exceeding the max length of the url when testing more complex searches.

The bug is in these methods where I extract the "settings" object into arrays (argNames and argValues). I'll fix this asap.

**Comment by gunjandatta** [comment]
@ndelacour Thank you for the help on this bug. It was very helpful to pin point the issue (argValues being null). I tested v2.0.2 with the same request:
```
var results = $REST.Search().searchquery({ Querytext: "test" }).executeAndWait()
```
The network tab showed the GET request w/ the url:
```
https://dattabase.sharepoint.com/sites/dev/_api/search/query(Querytext='test')
```
So it's taking the search settings now. Let me know if there is still an issue, or close the issue out if it's fixed.

@jpalo Thanks for the initial post, leading to this bug fix.

**Comment by ndelacour** [comment]
Thanks for the fix, I will test it later today. From looking at the code, it should be working correctly.
Interesting point on the postquery! A project here at work had to deal with larger query strings, I will check if this can help them.

**Comment by ndelacour** [comment]
I did some extra testing and your fix seems to be OK, when you are not working within an AddIn. Since it is not the same topic, I will open another issue for this. For me, this item can be closed.

**Comment by jpalo** [comment]
Thank you both for assistance to a question I thought was a simple one :D
